import fs from "fs";
import path from "path";
import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const arg = process.argv[2];
const prod = (arg === "production");

// Optional: set OBSIDIAN_PLUGIN_DIR to your vault's plugin folder to auto-copy
// build output there on each dev rebuild. Leave unset for a normal build.
const vaultDir = process.env.OBSIDIAN_PLUGIN_DIR;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,

	plugins: [
		{
			name: "copy-to-vault",
			setup(build) {
				build.onEnd(() => {
					if (!prod && vaultDir) {
						fs.copyFileSync("main.js", path.join(vaultDir, "main.js"));
						fs.copyFileSync("styles.css", path.join(vaultDir, "styles.css"));
						fs.copyFileSync("manifest.json", path.join(vaultDir, "manifest.json"));
						console.log(`[${new Date().toLocaleTimeString()}] copied build output to vault`);
					}
				});
			}
		}
	]
});

if (arg) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	if (vaultDir) {
		fs.watchFile("styles.css", { interval: 500 }, () => {
			fs.copyFileSync("styles.css", path.join(vaultDir, "styles.css"));
			console.log(`[${new Date().toLocaleTimeString()}] copied styles.css to vault`);
		});
	}
}
